AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to launch an EC2 instance with key-value tags and cfn-init.

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
          files:
            /var/www/html/index.html:
              content: |
                <!DOCTYPE html>
                <html lang="en">
                <head>
                    <meta charset="UTF-8">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title>Sample HTML Template</title>
                    <link rel="stylesheet" href="styles.css">
                </head>
                <body>
                    <header>
                        <h1>MANU-KANUPARHTI</h1>
                        <nav>
                            <ul>
                                <li><a href="#home">OUR Home</a></li>
                                <li><a href="#about">LEMON GARDEN</a></li>
                                <li><a href="#services">KP LAKE</a></li>
                                <li><a href="#contact">KP STREETS</a></li>
                            </ul>
                        </nav>
                    </header>
                    <main>
                        <section id="home">
                            <h2>Home</h2>
                            <p>This is the home section of the website.</p>
                        </section>
                        <section id="about">
                            <h2>About</h2>
                            <p>This is the about section of the website.</p>
                        </section>
                        <section id="services">
                            <h2>Services</h2>
                            <p>This is the services section of the website.</p>
                        </section>
                        <section id="contact">
                            <h2>Contact</h2>
                            <p>This is the contact section of the website.</p>
                        </section>
                    </main>
                    <footer>
                        <p>&copy; 2024 My Website</p>
                    </footer>
                    <script src="scripts.js"></script>
                </body>
                </html>
              mode: '000644'
              owner: root
              group: root
          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true
                packages:
                  yum:
                    - httpd
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c11a84584d4e09dd  # Ensure this is a free tier eligible AMI ID
      KeyName: manupptr  # Replace with your actual key pair name
      IamInstanceProfile: 
        Ref: InstanceProfile  # Reference to the instance profile to attach
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          exec > /var/log/user-data.log 2>&1
          yum update -y
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource MyEC2Instance --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource MyEC2Instance --region ${AWS::Region}
      Tags:
      - Key: Name
        Value: MyFreeInstance
      - Key: Environment
        Value: Development
      - Key: Project
        Value: MyProject
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M  # 15 minutes

  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties: 
      Roles: 
        - !Ref InstanceRole

  InstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowCFN
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStackResource
                  - cloudformation:SignalResource
                Resource: "*"

  Outputs:
    InstanceId:
      Description: The instance ID
      Value: !Ref MyEC2Instance
