AWSTemplateFormatVersion: "2010-09-09"
Description:
  This template creates a vpc in selected region
  author:Manu
Resources:
  MyCfnVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      Tags:
      - key: Name
        value: MyTestVPC
      - key: env
        value: Prod
      - key: department
        value: DevOps