AWSTemplateFormatVersion: "2010-09-09"
Description:
  This template creates a vpc in selected region
  author:Manu
  organization:ABCD
parameters:
  vpccidrblock:
    description: cirdblock modifying
    type: string
    default: 192.168.0.0/16
Resources:
  MyCfnVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref vpccidrblock
      Tags:
      - Key: Name
        Value: MyOwnVPC
      - Key: environment
        Value: Prod
      - Key: department
        Value: DevOps